# Generated by Django 5.2.8 on 2025-11-10 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('join_code', models.CharField(max_length=20, unique=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('draw_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winners_count', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_giveaways', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'giveaway')},
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('prize_description', models.TextField(blank=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.giveaway')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='main.participant')),
            ],
            options={
                'unique_together': {('participant', 'giveaway')},
            },
        ),
    ]
